In [1]:
import pandas as pd
import numpy as np
import random
# 设置全局Seed
np.random.seed(1)

# 文件读取：一种特殊类型的表格文件
train = pd.read_table('user_tag_query.10W.TRAIN',
                      encoding='gb18030',
                      header=None,
                      sep='\n',
                      names=['col'])
# 重新定义表格
train['ID'] = train['col'].apply(lambda x: x.split('\t')[0])
train['age'] = train['col'].apply(lambda x: x.split('\t')[1])
train['Gender'] = train['col'].apply(lambda x: x.split('\t')[2])
train['Education'] = train['col'].apply(lambda x: x.split('\t')[3])
# 内容：使用,进行拼接
train['Query'] = train['col'].apply(lambda x: ','.join(x.split('\t')[4:-1]))
# 对行别、年龄、教育程度进行过滤
train = train.drop(list(train[(train['age'] == '0') | (train['Gender'] == '0')
                              | (train['Education'] == '0')].index),
                   axis=0)
# 找到三种标签相同的人群进行gb 并提取信息
train_new = train.groupby(
    ['age', 'Gender', 'Education'],
    as_index=False).apply(lambda x: x['Query'].str.cat(sep=','))

In [2]:
train

,col,ID,age,Gender,Education,Query
0,22DD920316420BE2DF8D6EE651BA174B\t1\t1\t4\t柔和双...,22DD920316420BE2DF8D6EE651BA174B,1,1,4,"柔和双沟,女生,中财网首页 财经,http://pan.baidu.com/s/1plpjt..."
1,43CC3AF5A8D6430A3B572337A889AFE4\t2\t1\t3\t广州厨...,43CC3AF5A8D6430A3B572337A889AFE4,2,1,3,"广州厨宝烤箱,世情薄,人情恶,雨送黄昏花易落,晓风干,泪痕,厦门酒店用品批发市场,我只是不想..."
3,6931EFC26D229CCFCEA125D3F3C21E57\t4\t2\t3\t最受欢...,6931EFC26D229CCFCEA125D3F3C21E57,4,2,3,"最受欢迎狗狗排行榜,舶怎么读,场景描 写范例,三维绘图软件,枣和酸奶能一起吃吗,好不壮观,租..."
4,E780470C3BB0D340334BD08CDCC3C71A\t2\t2\t4\t干槽症...,E780470C3BB0D340334BD08CDCC3C71A,2,2,4,"干槽症能自愈吗,太太万岁叶舒心去没去美国,干槽症,右眼皮下面一直跳是怎么回事,麦当劳麦旋风的..."
6,0D58894CD481D4B3039000661665C0DB\t3\t2\t3\t貔貅饲...,0D58894CD481D4B3039000661665C0DB,3,2,3,"貔貅饲育指南,韩姨,贵阳学古琴,洛基,风速狗,综英美]店主不好吃,>重生之被拐儿童寻家记,锦..."
...,...,...,...,...,...,...
99995,E797FFCDCAF3899AB4D17B61170D8BFF\t1\t1\t5\t梦三生...,E797FFCDCAF3899AB4D17B61170D8BFF,1,1,5,"梦三生,逆行天后漫画结局,英雄联盟角色介绍大全,韩剧网最新韩国电视剧,119宣传语是什,斗破..."
99996,E06375F7D092ABDE78C2D79E4725D6B0\t1\t1\t5\t中国军...,E06375F7D092ABDE78C2D79E4725D6B0,1,1,5,"中国军队配枪,女生,央视版权问题,重庆,一次性手术刀,精神枷锁,人民检察官,舆论,精神禁锢,..."
99997,D55119CB0B9366B20974522B58C00912\t2\t2\t5\t英文翻...,D55119CB0B9366B20974522B58C00912,2,2,5,"英文翻译,幼儿园面试讲课,学前教育书第二版,shock to,幼儿园教师资格证面试讲课,设计..."
99998,EB4DBBD602C6459A19A77F09035E170C\t3\t2\t3\t哈尔滨...,EB4DBBD602C6459A19A77F09035E170C,3,2,3,"哈尔滨祖研中医院地址,指甲盖侧面的肉怎么是白色,补骨质有副作用吗,哈尔滨去呼兰,黑龙江祖研中..."
99999,61CF81DB79423CB89E5DAA752BC4D9DD\t1\t2\t5\t陈翔毛...,61CF81DB79423CB89E5DAA752BC4D9DD,1,2,5,"陈翔毛晓彤分手,青春偶像剧校园电影,九尾狐家族,王俊凯小说,女娲的成长日记女娲变身,闺蜜头像..."

In [3]:
df = pd.DataFrame(train_new)
# 统计每种有多少个
c = train.groupby(['age','Gender','Education'],as_index = False).count()

In [4]:
df.head()

                                                                      0
age Gender Education
1   1      1          今日说法,三一车载泵步行电机脉冲限幅是多少,百度,孟庭丽,中联重科官方网,诺基亚 c 1,三...
           2          高虹镇,今年台风最新消息,刘赙,嘉庆,2016台风最新消息,2016年12号台风,其貌不扬,...
           3          常州房价最新状况,天地源橄榄湾,模塑科技,定金能退吗,无锡东绛实验学校,相城殡仪馆啥时搬迁,...
           4          柔和双沟,女生,中财网首页 财经,http://pan.baidu.com/s/1plpjt...
           5          李明霖在哪直播,英文翻译,薄荷籽,为什么搜狐视频不能缓存,有一首歌女生唱的歌词是冬天什么什么...

In [5]:
c.head()

  age Gender Education    col     ID  Query
0   1      1         1      2      2      2
1   1      1         2      3      3      3
2   1      1         3    108    108    108
3   1      1         4   1423   1423   1423
4   1      1         5  19366  19366  19366

In [6]:
# 随机生成数据
def random_query(data, age, gender, edu):
    L = []
    df = pd.DataFrame()
    count1 = int(c[(c['age'] == str(age)) & (c['Gender'] == str(gender)) &
                   (c['Education'] == str(edu))]['ID'])
    count = count1 // 50  #if count1>100 else count1
    # 构建具体的词条表
    query = (data.loc[str(age), str(gender), str(edu)].values[0]).split(',')
    for i in range(count):
        # 从词条表种随机抽取（n条数据）
        L.append(random.sample(query, random.randint(18, len(query))))
    df['Query'] = L
    df['age'] = age
    df['Gender'] = gender
    df['Education'] = edu
    yield df

In [7]:
T = pd.DataFrame()
for age in range(1, 7):
    for gender in range(1, 2):
        for edu in range(1, 7):
            T = T.append(random_query(df, age, gender, edu).__next__())

In [12]:
T.to_csv('user_tag_T60.csv', encoding='gb18030')

In [8]:
tt = T.groupby(['age','Gender','Education'],as_index = False).count()

In [9]:
T.head(10)

                                               Query  age  Gender  Education
0  [我, 海水观赏鱼品种, 汉唐盛世, 丰田, 柚原春夏, 咪咕, 继承者们韩语字幕, 阴茎勃...    1       1          3
1  [好鸟归来第一段景物描写, 欧洲名气最大的统帅, new era帽子, 哈尔滨大学宿舍晚上断...    1       1          3
0  [进击的巨人之, 悦达起亚k2, 春之怀古, 饥荒安卓单机版破解版, 邵东到衡阳的汽车要多久...    1       1          4
1  [假口令红包代码, 奥巴马, 寡妇门前是非多是什么意思, 自己想搞一个加工的, 蒲城, 北汽...    1       1          4
2  [苹果手机单机3d游戏, 奥黛丽赫本, 南昌木吧酒吧, 萨弗兰斯基, 项滢璇, 乐视2手机怎...    1       1          4
3  [是英, 王者荣耀关羽的铭文, so是什么意思啊, 用输液吗, 袋鼠皮带价格, 紫色洋葱观测...    1       1          4
4  [老婆出轨后不让老公碰, 各类主体对风险管理技术适用?重庆双山科目一考试地址, 三国群英传8...    1       1          4
5  [wow7.0神器, 深圳海底捞火锅招聘, 夺舍, 为什么幸运召唤师抽不了, 显卡花屏, 致...    1       1          4
6  [欢乐斗地主, 面相算命图解大全, 博尔特被逼婚, 世界三大啤酒节举办地, 给狗办个证多少钱...    1       1          4
7  [肝功是抽血吗, 一般下了火车出口在哪里, 蓝海怎么撸, 葫芦侠, 大主宰, cf9月10号...    1       1          4

In [10]:
T.shape

(1018, 4)

In [11]:
T.tail()

                                                Query  age  Gender  Education
7   [朱允文, 罗海琼, 苗可秀,  ?氯雷他定片是息斯敏吗, 绿间真太郎的哥哥, 大同华润燃气...    5       1          4
8   [淘宝魔幻车神玩具, 青蛙荷花图片大全, 长春建工新吉润建设有限公司, 偷内吧, 重生之空间...    5       1          4
9   [学校新闻, 云南白药喷雾剂, 手机拍照发朋友圈被压缩了, 盐酸氟桂利嗪胶囊价格, 超级中华...    5       1          4
10  [小满是几月几日, 金刚藤手镯, 业火的向日葵, 封建解词, 2016年足球乙级联赛排位表,...    5       1          4
0   [手机录音在哪里找, 日语在线翻译, 李冉, 套色版画, 李胜岐, 崖柏的功效, 悠悠历史长...    6       1          4